export const PERSONALITY_DIMENSIONS = [
  { key: "formality", label: "Formality", lowLabel: "Formal", highLabel: "Casual" },
  { key: "warmth", label: "Warmth", lowLabel: "Clinical", highLabel: "Empathetic" },
  { key: "enthusiasm", label: "Enthusiasm", lowLabel: "Reserved", highLabel: "Energetic" },
  { key: "directness", label: "Directness", lowLabel: "Diplomatic", highLabel: "Blunt" },
  { key: "verbosity", label: "Verbosity", lowLabel: "Concise", highLabel: "Elaborate" },
  { key: "humor", label: "Humor", lowLabel: "Serious", highLabel: "Playful" },
  { key: "confidence", label: "Confidence", lowLabel: "Hedging", highLabel: "Assertive" },
  { key: "creativity", label: "Creativity", lowLabel: "Conventional", highLabel: "Inventive" },
]

export const PERSONALITY_PRESETS: Record<string, Record<string, number>> = {
  Professional: {
    formality: 0.3,
    warmth: 0.5,
    enthusiasm: 0.4,
    directness: 0.6,
    verbosity: 0.4,
    humor: 0.2,
    confidence: 0.7,
    creativity: 0.4,
  },
  Friendly: {
    formality: 0.7,
    warmth: 0.8,
    enthusiasm: 0.7,
    directness: 0.5,
    verbosity: 0.6,
    humor: 0.6,
    confidence: 0.6,
    creativity: 0.5,
  },
  Expert: {
    formality: 0.2,
    warmth: 0.3,
    enthusiasm: 0.3,
    directness: 0.8,
    verbosity: 0.5,
    humor: 0.1,
    confidence: 0.9,
    creativity: 0.3,
  },
  Creative: {
    formality: 0.6,
    warmth: 0.6,
    enthusiasm: 0.8,
    directness: 0.4,
    verbosity: 0.7,
    humor: 0.7,
    confidence: 0.6,
    creativity: 0.9,
  },
  Executor: {
    formality: 0.3,
    warmth: 0.3,
    enthusiasm: 0.3,
    directness: 0.9,
    verbosity: 0.2,
    humor: 0.0,
    confidence: 0.9,
    creativity: 0.2,
  },
}
